---
title: "fun"
author: "Nolan Meyer"
date: "3/25/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
library(tidyverse)
library(dplyr) 
library(readr)
library(broom)
library(ggplot2)
library(ggmosaic)
library(ggtext)
```

```{r}
us_18Q1 <- read_csv("us_18Q1.csv")

#Create new dataframe called "eighteen" that filters original data to only 18-24 year-old current college students
eighteen <- us_18Q1 %>% 
  filter(DEM_AGE10 == 1,
         DEM_COLLEGE == 1,
         DEM_STDNT == 1) %>% 
  mutate(any_chronic = (PAIN_CHRONIC != 1),
         any_alc = (ALC_USE != 1),
         rxsafe = (RXDRUGSAFE_HIGH == 1),
         any_mental = (MENT_ANX == 1 | MENT_ADHD == 1 | MENT_AUT == 1 | MENT_BIP == 1 | MENT_BPD == 1 | MENT_DEP == 1 | MENT_EAT == 1),
         curr_tob = (TOB_USE == 1))
```


```{r}
#PHARMACEUTICAL/PRESCRIPTION opioids non-medical use
eighteen %>% 
  select(ends_with("NMU")) %>% 
  rename(Fentanyl = FENT_NMU,
         Buprenorphine = BUP_NMU,
         Methadone = METH_NMU,
         Morphine = MORPH_NMU,
         Oxycodone = OXY_NMU,
         Oxymorphone = OXYM_NMU,
         Tramadol = TRAM_NMU,
         Tapentadol = TAP_NMU,
         Hydrocodone = HYD_NMU,
         Hydromorphone = HYDM_NMU,
         Sufentanil = SUF_NMU,
         Codeine = COD_NMU,
         Dihydrocodeine = DIHY_NMU) %>% 
  replace(is.na(.), 0) %>% 
  summarise_all(funs(sum)) %>% 
  pivot_longer(cols = Fentanyl:Dihydrocodeine,
               names_to = "drug",
               values_to = "num") %>% 
  ggplot(aes(x = num, y = fct_reorder(drug, num))) +
  geom_col(fill = "#21C09C") +
  labs(title = "Non-medical use of prescription opioids by college students aged 18-24 in 2018", x = "", y = "", caption = "Totals out of 1,277 college students aged 18-24 surveyed in 2018") +
  theme(plot.title = element_text(size = 13, face = "bold", hjust = 1.35, colour = "Black"),
        plot.subtitle = element_text(colour = "Black"),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank(),
        plot.background = element_rect(fill = "lightgrey"),
        panel.background = element_rect(fill = "lightgrey"),
        axis.text.x = element_text(size = 9, colour = "Black"),
        axis.text.y = element_text(size = 10, colour = "Black")
        )
```



```{r}
#Adding indicator of ANY non-medical prescription opioid use (18-24 in college)
eighteen_nmu <- eighteen %>% 
  select(ends_with("NMU")) %>% 
  rename(Fentanyl = FENT_NMU,
         Buprenorphine = BUP_NMU,
         Methadone = METH_NMU,
         Morphine = MORPH_NMU,
         Oxycodone = OXY_NMU,
         Oxymorphone = OXYM_NMU,
         Tramadol = TRAM_NMU,
         Tapentadol = TAP_NMU,
         Hydrocodone = HYD_NMU,
         Hydromorphone = HYDM_NMU,
         Sufentanil = SUF_NMU,
         Codeine = COD_NMU,
         Dihydrocodeine = DIHY_NMU) %>% 
  select(Fentanyl:Dihydrocodeine) %>% 
  replace(is.na(.), 0) %>%
  mutate(any_nmu = (Fentanyl == 1 | Buprenorphine == 1 | Methadone == 1 | Morphine == 1 | Oxycodone == 1 |Oxymorphone == 1 | Tramadol == 1 | Tapentadol == 1 | Hydrocodone == 1 | Hydromorphone == 1 | Sufentanil == 1 | Codeine == 1 | Dihydrocodeine == 1)) %>% 
  mutate(any_nmu_numeric = as.numeric(any_nmu == TRUE), ID = c(1:1277))

eighteen_nmu

eighteen_nmu %>% 
  count(any_nmu)
```



```{r}
#Adding the *any_nmu_numeric* variable to the "eighteen" dataframe

eighteen <- eighteen %>% 
  mutate(ID = c(1:1277))

eighteen$any_nmu_numeric <- eighteen_nmu$any_nmu_numeric[match(eighteen$ID, eighteen_nmu$ID)]
```


```{r}
#Adding indicator of ANY non-medical prescription opioid use (NOT 18-24 in college)
not_eighteen <- us_18Q1 %>% 
  filter(DEM_AGE10 != 1,
         is.na(DEM_COLLEGE),
         DEM_STDNT != 1)

not_eighteen_nmu <- not_eighteen %>% 
  select(ends_with("NMU")) %>% 
  rename(Fentanyl = FENT_NMU,
         Buprenorphine = BUP_NMU,
         Methadone = METH_NMU,
         Morphine = MORPH_NMU,
         Oxycodone = OXY_NMU,
         Oxymorphone = OXYM_NMU,
         Tramadol = TRAM_NMU,
         Tapentadol = TAP_NMU,
         Hydrocodone = HYD_NMU,
         Hydromorphone = HYDM_NMU,
         Sufentanil = SUF_NMU,
         Codeine = COD_NMU,
         Dihydrocodeine = DIHY_NMU) %>% 
  select(Fentanyl:Dihydrocodeine) %>% 
  replace(is.na(.), 0) %>%
  mutate(any_nmu = (Fentanyl == 1 | Buprenorphine == 1 | Methadone == 1 | Morphine == 1 | Oxycodone == 1 |Oxymorphone == 1 | Tramadol == 1 | Tapentadol == 1 | Hydrocodone == 1 | Hydromorphone == 1 | Sufentanil == 1 | Codeine == 1 | Dihydrocodeine == 1))

not_eighteen_nmu %>% 
  count(any_nmu)
```

```{r}
#Adding indicator of ANY non-medical prescription opioid use (everybody)
total_nmu <- us_18Q1 %>% 
  filter((DEM_AGE10 == 1 & DEM_COLLEGE == 1 & DEM_STDNT == 1) | (DEM_AGE10 != 1 & is.na(DEM_COLLEGE) & DEM_STDNT != 1)) %>% #filters in college and 18-24 or not in college AND not 18-24
  rename(Fentanyl = FENT_NMU,
         Buprenorphine = BUP_NMU,
         Methadone = METH_NMU,
         Morphine = MORPH_NMU,
         Oxycodone = OXY_NMU,
         Oxymorphone = OXYM_NMU,
         Tramadol = TRAM_NMU,
         Tapentadol = TAP_NMU,
         Hydrocodone = HYD_NMU,
         Hydromorphone = HYDM_NMU,
         Sufentanil = SUF_NMU,
         Codeine = COD_NMU,
         Dihydrocodeine = DIHY_NMU) %>% 
  select(DEM_AGE10,
         DEM_COLLEGE,
         DEM_STDNT,
         Fentanyl:Dihydrocodeine) %>% 
  mutate(is_college_18_24 = (DEM_AGE10 == 1 & DEM_COLLEGE == 1 & DEM_STDNT == 1),
         is_not_college_18_24 = (DEM_AGE10 != 1 & is.na(DEM_COLLEGE) & DEM_STDNT != 1)) %>% 
  replace(is.na(.), 0) %>%
  mutate(any_nmu = (Fentanyl == 1 | Buprenorphine == 1 | Methadone == 1 | Morphine == 1 | Oxycodone == 1 |Oxymorphone == 1 | Tramadol == 1 | Tapentadol == 1 | Hydrocodone == 1 | Hydromorphone == 1 | Sufentanil == 1 | Codeine == 1 | Dihydrocodeine == 1)) 

total_nmu %>% 
  count(is_college_18_24, any_nmu) %>% 
  arrange(n)
```


```{r}
#Stacked bar plot of NMU in college 18-24 vs not
total_nmu %>% 
ggplot(aes(x = is_college_18_24, fill = any_nmu)) +
  geom_bar(position = "fill") +
  scale_y_continuous(labels = scales::percent) +
  geom_text(aes(label = "18.64%", x = 2, y = 0.0932)) +
  geom_text(aes(label = "12.00%", x = 1, y = 0.06)) +
  labs(title = "Non-medical use (NMU) of prescription opioids in 2018", x = "18-24 years old and in college", y = "") +
  scale_fill_manual(name = "NMU", labels = c("No", "Yes"), values = c("#3881B6", "#D7864C")) +
  theme(plot.title = element_text(size = 13, face = "bold", hjust = -0.5, colour = "Black"),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank(),
        plot.background = element_rect(fill = "ivory"),
        panel.background = element_rect(fill = "ivory"),
        legend.background = element_rect(fill = "ivory"),
        axis.text.x = element_text(size = 8, colour = "Black"),
        axis.text.y = element_text(size = 8, colour = "Black"))
```

```{r}
a <- us_18Q1 %>% 
  filter(DEM_AGE10 == 1,
         DEM_COLLEGE == 1,
         DEM_STDNT == 1) %>% 
  rename(Fentanyl = FENT_NMU,
         Buprenorphine = BUP_NMU,
         Methadone = METH_NMU,
         Morphine = MORPH_NMU,
         Oxycodone = OXY_NMU,
         Oxymorphone = OXYM_NMU,
         Tramadol = TRAM_NMU,
         Tapentadol = TAP_NMU,
         Hydrocodone = HYD_NMU,
         Hydromorphone = HYDM_NMU,
         Sufentanil = SUF_NMU,
         Codeine = COD_NMU,
         Dihydrocodeine = DIHY_NMU) %>% 
  replace(is.na(.), 0) %>%
  mutate(any_nmu = (Fentanyl == 1 | Buprenorphine == 1 | Methadone == 1 | Morphine == 1 | Oxycodone == 1 |Oxymorphone == 1 | Tramadol == 1 | Tapentadol == 1 | Hydrocodone == 1 | Hydromorphone == 1 | Sufentanil == 1 | Codeine == 1 | Dihydrocodeine == 1))

b <- a %>% 
  mutate(any_chronic = (PAIN_CHRONIC != 1),
         any_alc = (ALC_USE != 1))

#Regression model on greek life: Significant
glm.mod <- a %>% with(glm(any_nmu ~ COLLEGE_GREEK, family = binomial))
glm.mod
tidy(glm.mod)
exp(confint(glm.mod)) %>% round(2)

glm.mod1 <- b %>% with(glm(any_nmu ~ any_chronic, family = binomial))
glm.mod1
tidy(glm.mod1)
exp(confint(glm.mod1)) %>% round(2)

glm.mod2 <- b %>% with(glm(any_nmu ~ any_alc, family = binomial))
glm.mod2
tidy(glm.mod2)
exp(confint(glm.mod2)) %>% round(2)
```



```{r}
#Multiple logistic regression exploration of variables potentially related with non-medical use of opioids, *any_nmu_numeric*

#State: Non-Significant
glm_fit <- glm(any_nmu_numeric ~ DEM_STATE, data = eighteen, family = binomial)
summary(glm_fit)

#Region: Non-Significant
glm_fit <- glm(any_nmu_numeric ~ DEM_REGION, data = eighteen, family = binomial)
summary(glm_fit)

#Gender: Highly Significant. Negative coefficient, so males are more likely than females for NMU
glm_fit1 <- glm(any_nmu_numeric ~ DEM_GENDER, data = eighteen, family = binomial)
summary(glm_fit1)

#Age: Significant at 0.05 level. Positive coefficient, so older individuals more likely
glm_fit2 <- glm(any_nmu_numeric ~ DEM_AGE, data = eighteen, family = binomial)
summary(glm_fit2)

#Hispanic: Non-Significant
glm_fit <- glm(any_nmu_numeric ~ DEM_HISPANIC, data = eighteen, family = binomial)
summary(glm_fit)

#Race: Non-Significant here, but this isn't a good way to look at it (Race is coded as quantitative in the dataframe)
glm_fit <- glm(any_nmu_numeric ~ DEM_RACE, data = eighteen, family = binomial)
summary(glm_fit)

#Income: Non-significant
glm_fit <- glm(any_nmu_numeric ~ DEM_INCOME, data = eighteen, family = binomial)
summary(glm_fit)

#College Size: Non-Significant
glm_fit <- glm(any_nmu_numeric ~ COLLEGE_SIZE, data = eighteen, family = binomial)
summary(glm_fit)

#College Housing: Significant. Positive coefficient so students living in on-campus housing are more likely for NMU. Counter-Intuitive??
glm_fit3 <- glm(any_nmu_numeric ~ COLLEGE_HOUSING, data = eighteen, family = binomial)
summary(glm_fit3)

glm_fit4 <- glm(any_nmu_numeric ~ COLLEGE_GREEK + DEM_GENDER + any_chronic + any_alc + rxsafe + any_mental + curr_tob, data = eighteen, family = binomial)
summary(glm_fit4)

glm_fit5 <- glm(any_nmu_numeric ~ any_chronic, data = eighteen, family = binomial)
summary(glm_fit5)

glm_fit6 <- glm(any_nmu_numeric ~ any_alc, data = eighteen, family = binomial)
summary(glm_fit6)

glm_fit8 <- glm(any_nmu_numeric ~ rxsafe, data = eighteen, family = binomial)
summary(glm_fit8)

glm_fit10 <- glm(any_nmu_numeric ~ any_mental, data = eighteen, family = binomial)
summary(glm_fit10)

glm_fit11 <- glm(any_nmu_numeric ~ curr_tob, data = eighteen, family = binomial)
summary(glm_fit11)
```



```{r}
#Mental Illness Diagnoses as a Predictor for *any_nmu_numeric*

#Anxiety: Highly significant
glm_fit <- glm(any_nmu_numeric ~ MENT_ANX, data = eighteen, family = binomial)
summary(glm_fit)

#ADHD: Significant
glm_fit <- glm(any_nmu_numeric ~ MENT_ADHD, data = eighteen, family = binomial)
summary(glm_fit)

#Autism: Significant
glm_fit <- glm(any_nmu_numeric ~ MENT_AUT, data = eighteen, family = binomial)
summary(glm_fit)

#Bipolar: Highly significant
glm_fit <- glm(any_nmu_numeric ~ MENT_BIP, data = eighteen, family = binomial)
summary(glm_fit)

#Borderline Personality Disorder: Highly significant
glm_fit <- glm(any_nmu_numeric ~ MENT_BPD, data = eighteen, family = binomial)
summary(glm_fit)

#Depression: Highly significant
glm_fit <- glm(any_nmu_numeric ~ MENT_DEP, data = eighteen, family = binomial)
summary(glm_fit)

#Eating Disorder: Highly significant
glm_fit <- glm(any_nmu_numeric ~ MENT_EAT, data = eighteen, family = binomial)
summary(glm_fit)

#OCD: Non-significant
glm_fit <- glm(any_nmu_numeric ~ MENT_OCD, data = eighteen, family = binomial)
summary(glm_fit)

#Panic Disorder: Non-significant
glm_fit <- glm(any_nmu_numeric ~ MENT_PPD, data = eighteen, family = binomial)
summary(glm_fit)

#PTSD: Non-significant
glm_fit <- glm(any_nmu_numeric ~ MENT_PTSD, data = eighteen, family = binomial)
summary(glm_fit)

#Schizophrenia: Slightly significant
glm_fit <- glm(any_nmu_numeric ~ MENT_SCH, data = eighteen, family = binomial)
summary(glm_fit)

#Other: Non-significant
glm_fit <- glm(any_nmu_numeric ~ MENT_OTH, data = eighteen, family = binomial)
summary(glm_fit)

#Variables that are significant predictors of *any_nmu_numeric* individually: MENT_ANX, MENT_ADHD, MENT_AUT, MENT_BIP, MENT_BPD, MENT_DEP, MENT_EAT, and MENT_SCH
```





```{r}
threshold <- 0.25

glm_fit4 %>%
  augment(type.predict = "response") %>%
  mutate(predict_NMU_Use = .fitted >= threshold) %>%
  count(any_nmu_numeric, predict_NMU_Use)

augment(glm_fit4, type.predict = 'response') %>%
  ggplot(aes(x = factor(any_nmu_numeric), y = .fitted)) +
  geom_boxplot() +
  labs(x = 'NMU of prescription opioids', y = 'Predicted Probability of NMU of prescription opioids') + 
  theme_classic()
```



